languages:
  JavaScript: true
exclude_paths:
- "lib/*"
- "test/*"
- "dist/*"
- "gulpfile.js"
- "examples/*"
- "webpack.config.base.js"
- "webpack.config.development.js"
- "webpack.config.production.js"
