language: node_js
node_js:
  - "0.10"
  - "0.12"
  - "io.js"
branches:
  only:
    - master
sudo: false
script: "gulp coverage"
after_success:
  - npm install -g codeclimate-test-reporter
  - CODECLIMATE_REPO_TOKEN=df2b3e42fca948c2aa36732454d743cff99e68cbd062258a87b056b182471caf codeclimate-test-reporter < coverage/lcov.info
